import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { getLocale } from "next-intl/server";
import type { ReactNode } from "react";
import { defaultLocale } from "@/i18n/locales";
import "./globals.scss";
import Providers from "./providers";

const geistSans = Geist({
  weight: ["400", "500", "600", "700"],
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const locale = (await getLocale()) ?? defaultLocale;

  return (
    <html lang={locale}>
      <body className={geistSans.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
